// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NTHU-LSALAB/NTHU-Distributed-System/modules/video/pb (interfaces: Video_UploadVideoServer,VideoClient)

// Package pbmock is a generated GoMock package.
package pbmock

import (
	context "context"
	reflect "reflect"

	pb "github.com/NTHU-LSALAB/NTHU-Distributed-System/modules/video/pb"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockVideo_UploadVideoServer is a mock of Video_UploadVideoServer interface.
type MockVideo_UploadVideoServer struct {
	ctrl     *gomock.Controller
	recorder *MockVideo_UploadVideoServerMockRecorder
}

// MockVideo_UploadVideoServerMockRecorder is the mock recorder for MockVideo_UploadVideoServer.
type MockVideo_UploadVideoServerMockRecorder struct {
	mock *MockVideo_UploadVideoServer
}

// NewMockVideo_UploadVideoServer creates a new mock instance.
func NewMockVideo_UploadVideoServer(ctrl *gomock.Controller) *MockVideo_UploadVideoServer {
	mock := &MockVideo_UploadVideoServer{ctrl: ctrl}
	mock.recorder = &MockVideo_UploadVideoServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideo_UploadVideoServer) EXPECT() *MockVideo_UploadVideoServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockVideo_UploadVideoServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockVideo_UploadVideoServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockVideo_UploadVideoServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockVideo_UploadVideoServer) Recv() (*pb.UploadVideoRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*pb.UploadVideoRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockVideo_UploadVideoServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockVideo_UploadVideoServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockVideo_UploadVideoServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockVideo_UploadVideoServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockVideo_UploadVideoServer)(nil).RecvMsg), arg0)
}

// SendAndClose mocks base method.
func (m *MockVideo_UploadVideoServer) SendAndClose(arg0 *pb.UploadVideoResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockVideo_UploadVideoServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockVideo_UploadVideoServer)(nil).SendAndClose), arg0)
}

// SendHeader mocks base method.
func (m *MockVideo_UploadVideoServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockVideo_UploadVideoServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockVideo_UploadVideoServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockVideo_UploadVideoServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockVideo_UploadVideoServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockVideo_UploadVideoServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockVideo_UploadVideoServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockVideo_UploadVideoServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockVideo_UploadVideoServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockVideo_UploadVideoServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockVideo_UploadVideoServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockVideo_UploadVideoServer)(nil).SetTrailer), arg0)
}

// MockVideoClient is a mock of VideoClient interface.
type MockVideoClient struct {
	ctrl     *gomock.Controller
	recorder *MockVideoClientMockRecorder
}

// MockVideoClientMockRecorder is the mock recorder for MockVideoClient.
type MockVideoClientMockRecorder struct {
	mock *MockVideoClient
}

// NewMockVideoClient creates a new mock instance.
func NewMockVideoClient(ctrl *gomock.Controller) *MockVideoClient {
	mock := &MockVideoClient{ctrl: ctrl}
	mock.recorder = &MockVideoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoClient) EXPECT() *MockVideoClientMockRecorder {
	return m.recorder
}

// DeleteVideo mocks base method.
func (m *MockVideoClient) DeleteVideo(arg0 context.Context, arg1 *pb.DeleteVideoRequest, arg2 ...grpc.CallOption) (*pb.DeleteVideoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteVideo", varargs...)
	ret0, _ := ret[0].(*pb.DeleteVideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteVideo indicates an expected call of DeleteVideo.
func (mr *MockVideoClientMockRecorder) DeleteVideo(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVideo", reflect.TypeOf((*MockVideoClient)(nil).DeleteVideo), varargs...)
}

// GetVideo mocks base method.
func (m *MockVideoClient) GetVideo(arg0 context.Context, arg1 *pb.GetVideoRequest, arg2 ...grpc.CallOption) (*pb.GetVideoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVideo", varargs...)
	ret0, _ := ret[0].(*pb.GetVideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideo indicates an expected call of GetVideo.
func (mr *MockVideoClientMockRecorder) GetVideo(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideo", reflect.TypeOf((*MockVideoClient)(nil).GetVideo), varargs...)
}

// Healthz mocks base method.
func (m *MockVideoClient) Healthz(arg0 context.Context, arg1 *pb.HealthzRequest, arg2 ...grpc.CallOption) (*pb.HealthzResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Healthz", varargs...)
	ret0, _ := ret[0].(*pb.HealthzResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Healthz indicates an expected call of Healthz.
func (mr *MockVideoClientMockRecorder) Healthz(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthz", reflect.TypeOf((*MockVideoClient)(nil).Healthz), varargs...)
}

// ListVideo mocks base method.
func (m *MockVideoClient) ListVideo(arg0 context.Context, arg1 *pb.ListVideoRequest, arg2 ...grpc.CallOption) (*pb.ListVideoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListVideo", varargs...)
	ret0, _ := ret[0].(*pb.ListVideoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideo indicates an expected call of ListVideo.
func (mr *MockVideoClientMockRecorder) ListVideo(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideo", reflect.TypeOf((*MockVideoClient)(nil).ListVideo), varargs...)
}

// UploadVideo mocks base method.
func (m *MockVideoClient) UploadVideo(arg0 context.Context, arg1 ...grpc.CallOption) (pb.Video_UploadVideoClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadVideo", varargs...)
	ret0, _ := ret[0].(pb.Video_UploadVideoClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadVideo indicates an expected call of UploadVideo.
func (mr *MockVideoClientMockRecorder) UploadVideo(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadVideo", reflect.TypeOf((*MockVideoClient)(nil).UploadVideo), varargs...)
}
